name: Pipeline 3

on:
  push:
    branches:
      - 'release-*'

env:
  DOCKER_HUB_USERNAME: awsomz
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Extract version from branch name
      run: echo "VERSION=${GITHUB_REF#refs/heads/release-}" >> $GITHUB_ENV

    - name: Build and push Docker images
      run: |
        docker build -t $DOCKER_HUB_USERNAME/devops-project-backend:${{ env.VERSION }} -f docker/backendDockerfile .
        docker push $DOCKER_HUB_USERNAME/devops-project-backend:${{ env.VERSION }}
        docker build -t $DOCKER_HUB_USERNAME/devops-project-frontend:${{ env.VERSION }} -f docker/frontendDockerfile .
        docker push $DOCKER_HUB_USERNAME/devops-project-frontend:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/release-*'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        echo "TAG=${{ env.VERSION }}" >> $GITHUB_ENV
        docker-compose -f docker/docker-compose.yml pull
        docker-compose -f docker/docker-compose.yml up -d
